### ISSUE TITLE
Is there any plan to support relationships?

### ISSUE THREAD

**Issue by craigedmunds** [json-api-dotnet/JsonApiDotNetCore.MongoDb#73]
The homepage says "JSON:API relationships are currently not supported. You can use complex object graphs though, which are stored in a single document.", our domain has some resources that aren't suitable for nesting so we want them in separate mongo collections with relationships between them.

**Comment by bkoelman** [comment]
Probably not anytime soon. This depends on https://jira.mongodb.org/projects/EF/issues/EF-117?filter=allopenissues, which is labeled FY25Q3. Please upvote or comment on that issue.

**Comment by craigedmunds** [comment]
Whilst that might be a helpful option; I don’t think it does depend on it… many of the other frameworks support it!

They just query the collections separately rather than expect the DB to do it.

**Comment by craigedmunds** [comment]
We’d be happy to look at implementing and raising a PR if it was wanted & a design agreed

**Comment by bkoelman** [comment]
I'm open to ideas. What design do you have in mind?

**Comment by craigedmunds** [comment]
I’m not familiar with the code yet so no idea! Just didn’t want to go away and do it and find we were taking it down a path that wasn’t wanted.

**Comment by bkoelman** [comment]
There's been some movement in the EF Core provider for MongoDB. It now supports saving and querying 1:1 and 1:N relationships. Many-to-many still doesn't work; it's tracked at https://jira.mongodb.org/browse/EF-454.
